### ISSUE TITLE
Set up your Kanban: Code review

### ISSUE THREAD

**Issue by kiboma2021** [kiboma2021/capstone-project-front-end#17]
**Links**

1. Link to front-end kanban [here](https://github.com/users/kiboma2021/projects/6)
2. Link to back-end kanban [here](https://github.com/users/kiboma2021/projects/5)

**Students**

- Kevin Cruz || @EvansSnave
- Zabi Noori || @ZabihullahNooriWardak
- Maro Monroy || @Movgto
- Ben Kiboma || @kiboma2021

**Kanban**

- Back-end:

![Screenshot from 2024-02-16 18-30-33](https://github.com/kiboma2021/capstone-project-front-end/assets/93031593/61788b41-60cb-4c9f-93d2-66b611664691)

- Front-end: 

![Screenshot from 2024-02-16 18-30-53](https://github.com/kiboma2021/capstone-project-front-end/assets/93031593/0cd2bae7-fa80-4309-b2b7-f09fd666321c)

**Comment by Meltrust** [comment]
## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings are now equal✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
